language: de_DE

bungeecord:
  servername: "CannonFight-Hub#1"

database:
  host: 127.0.0.1
  port: 27017
  database: CannonFight
  prefix: ''
  auth:
    username: CannonFight
    password: password
    db: auth_db

lobby:
  ==: org.bukkit.Location
  world: lobby
  x: 0
  y: 64
  z: 0