language: de_DE

database:
  host: 127.0.0.1
  port: 27017
  database: CannonFight
  prefix: ''
  auth:
    username: CannonFight
    password: CannonFight
    db: auth_db
    
game:
  time:
    start: 10
    play: 300
    gameover: 10
  reward: 20
  livesPerLive: 40