language: de_DE

database:
  host: "127.0.0.1"
  port: 3308
  database: "minecraft"
  prefix: "cannonfight_"
  auth:
    username: "minecraft"
    password: "password"
    db: "auth"
game:
  time:
    start: 10
    play: 300
    gameover: 10
  reward: 20