name: CannonFightGame
main: de.pesacraft.cannonfight.game.CannonFightGame
version: 0.1.0
author: FroznMine

commands:
  coins:
    description: Get the coins a player has.
    aliases: [cannonfightcoins, cfcoins, ccoins]
    usage: /coins [player]
  leave:
    description: Leave the game
    aliases: [cannonfightleave, cfleave, cleave]
    usage: /leave [player]
  shop:
    description: Open the shop
    aliases: [cannonfightshop, cfshop, cshop]
    usage: /shop [player]
  language-reload:
    description: Reload language file
    aliases: [langrl, langreload, rllang, reloadlang, languagereload]
    usage: /language-reload
  
permissions:
  cannonfight.command.*:
    children:
      cannonfight.command.coins.*: true
      cannonfight.command.leave.*: true
      cannonfight.command.shop.*: true
      cannonfight.command.language-reload: true
  
  cannonfight.command.language-reload:
    default: op
  
  cannonfight.command.coins.*:
    children:
      cannonfight.command.coins: true
      cannonfight.command.coins.other: true
  cannonfight.command.coins:
    default: true
  cannonfight.command.coins.other:
    default: op
  
  cannonfight.command.leave.*:
    children:
      cannonfight.command.leave: true
      cannonfight.command.leave.other: true  
  cannonfight.command.leave:
    default: true
  cannonfight.command.leave.other:
    default: op
  
  cannonfight.command.shop.*:
    children:
      cannonfight.command.shop: true
      cannonfight.command.shop.other: true
  cannonfight.command.shop:
    default: true
  cannonfight.command.shop.other:
    default: op